version: '3'
services:
  java:
    image: openjdk:8
    ports:
      - 80:8080
    volumes:
      - ./students-0.0.1-REST.jar:/app/app.jar
      - ./data:/app/data
    command: java -jar /app/app.jar
