version: '3'

services:


  reverse-proxy:
    # The official v2.0 Traefik docker image
    image: traefik:latest
    # Enables the web UI and tells Traefik to listen to docker
    command: --providers.docker
    ports:
      # The HTTP port
      - "80:80"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      - "name=rabbitmq"
      - "traefik.enable=false"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - '1883:1883'
      - '9001:9001'

  rest:
    image: openjdk:8
    volumes:
      - ./rest/students-0.0.1-REST.jar:/app/app.jar
      - ./rest/application.properties:/app/application.properties
      - ./rest/data:/app/data
    command: java -jar /app/app.jar --spring.config.location=/app/application.properties
    labels:
      - "traefik.http.routers.rest.rule=PathPrefix(`/v1`)"
      - "traefik.http.services.rest.loadbalancer.server.port=8080"

  rest_and_amqp:
    image: openjdk:8
    volumes:
      - ./amqp-server/students-0.0.2-AMQP-REST.jar:/app/app.jar
      - ./amqp-server/application.properties:/app/application.properties
      - ./amqp-server/data:/app/data
    command: java -jar /app/app.jar --spring.config.location=/app/application.properties
    labels:
      - "traefik.http.routers.rest-amqp.rule=PathPrefix(`/v2`)"
      - "traefik.http.services.rest-amqp.loadbalancer.server.port=8080"