version: '3'

services:


  reverse-proxy:
    # The official v2.0 Traefik docker image
    image: traefik:latest
    # Enables the web UI and tells Traefik to listen to docker
    command: --providers.docker
    ports:
      # The HTTP port
      - "80:80"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      - "name=rabbitmq"
      - "traefik.enable=false"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config


  rest:
    image: openjdk:8
    volumes:
      - ./students-0.0.1-REST.jar:/app/app.jar
      - ./data:/app/data
    command: java -jar /app/app.jar
    labels:
      - "traefik.http.middlewares.strip-rest.stripprefix.prefixes=/v1"
      - "traefik.http.middlewares.strip-rest.stripprefix.forceslash=true"
      - "traefik.http.middlewares.rest-redirectregex.redirectregex.regex=http://localhost/$$"
      - "traefik.http.middlewares.rest-redirectregex.redirectregex.replacement=http://localhost/v1/swagger-ui.html"
      - "traefik.http.routers.rest.rule=PathPrefix(`/v1`)"
      - "traefik.http.services.rest.loadbalancer.server.port=8080"
      - "traefik.http.routers.rest.middlewares=strip-rest@docker,rest-redirectregex@docker"